version: '3.7'
services: 
  web:
    build: "./docker"
    container_name: "centos"
    ports:
      - 20000:80
    volumes:
      - "./public:/var/www/html/public"
    privileged: true
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ***
      MYSQL_USER: ***
      MYSQL_PASSWORD: *****
      MYSQL_ROOT_PASSWORD: ***
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  mysql-data:

